### PR TITLE
Carray ext 1685 26

### PR DESCRIPTION
**Pull request by gnzsnz**
fix issue https://github.com/stefan-jansen/bcolz-zipline/issues/40

this PR applies change in carray_ext.pyx file and removes Cython < 3.0 restriction.

### CODE REVIEW

**Comment by gnzsnz** [comment]
@stefan-jansen please review, this should fix the issue with cython 3, https://github.com/stefan-jansen/bcolz-zipline/issues/40

**Comment by gnzsnz** [comment]
@andrebienemann maybe you can provide some inside here.

fix line 1685 in `bcolz/carray_ext.pyx` with `rsize = isize // newlen` and removing Cython3 restriction is causing "E TypeError: 'float' object cannot be interpreted as an integer"

**Comment by gnzsnz** [comment]
setting `# cython: language_level=2` should solve the issues according to the migration guide

https://cython.readthedocs.io/en/latest/src/userguide/migrating_to_cy30.html

however it's not working. i [updated cython](https://github.com/gnzsnz/bcolz-zipline/tree/language_level) files with languague_level=2

but it's still failing.

this is way beyond my comprehension. I'm afraid i can't do much more .

**Comment by andrebienemann** [comment]
@gnzsnz, we need some type casting here.

My appolagies for underenstimating the migrations effors.

I managed to resolve all errors on my end, though.

Happy to submit them on top of the changes in this pull request.

**Comment by gnzsnz** [comment]
@andrebienemann , that's awesome

you can pull from this branch https://github.com/gnzsnz/bcolz-zipline/tree/carray_ext_1685_26 and put your changes on top of it.

**Comment by andrebienemann** [comment]
@gnzsnz, it doesn't seem I have permissions to push my changes to that branch.

`
ERROR: Permission to gnzsnz/bcolz-zipline.git denied to andrebienemann.
`

**Comment by gnzsnz** [comment]
Hi,

I'm not an expert on this. the way i have do it in the past is to fork the repo, which will create a copy of the repo on my account, then do the changes on my account. and finally merge it into github.com/stefan-jansen/bcolz-zipline

hope this helps

**Comment by andrebienemann** [comment]
@gnzsnz, another way would be to invite me to collaborate on your fork. You could do it in the repository settings.

**Comment by andrebienemann** [comment]
@stefan-jansen, please review the PR. In addition to floor division and type-casting, this PR removes a deprecation warning for numpy. That deprecation warning is no longer valid since Cython 3 doesn't use numpy's deprecated C-API version anymore.

**Pull request merged**
